flowchart TD
  Start
  IncrementTurn[*State: IncrementTurn*]
  SelectingAction[*State: SelectingAction*]
  SelectingAttack[*State: SelectingAttack*]
  Attack[*State: Attack*]
  Info[*State: Info*]
  EnemyAttack[*State: EnemyAttack*]
  GameEnd[*State: GameEnd*]
  EnactStatuses[*State: EnactStatuses*]
  SelectingItem[*State: SelectingItem*]
  style SelectingItem stroke:#33cc33,stroke-width:4
  SelectingAttackPPRestore[*State: SelectingAttackPPRestore*]
  style SelectingAttackPPRestore stroke:#33cc33,stroke-width:4

  Start --> IncrementTurn

  IncrementTurn --> |Player Turn| SelectingAction
  SelectingAction --> |Attack menu selected| SelectingAttack
  SelectingAttack --> |specific attack selected| Attack

  SelectingAction --> |Item menu selected|SelectingItem
  linkStyle 4 stroke:#33cc33,stroke-width:4px
  SelectingItem --> |Specific consumable item selected|Info
  linkStyle 5 stroke:#33cc33,stroke-width:4px
  SelectingItem --> |PP Restore item selected|SelectingAttackPPRestore
  linkStyle 6 stroke:#33cc33,stroke-width:4px

  SelectingAttackPPRestore --> |specific attack selected|Info
  linkStyle 7 stroke:#33cc33,stroke-width:4px

  IncrementTurn --> |Enemy Turn| EnemyAttack
  EnemyAttack --> Attack

  Attack --> Info

  IncrementTurn --> |Player or Enemy Dead| GameEnd

  IncrementTurn --> |Statuses not enacted| EnactStatuses

  Info --> |No more messages| IncrementTurn
  Info --> |More messages to display| Info

  EnactStatuses --> Info
